FiWo = input("Введите первое слово: ")
FiWoSet = set(FiWo)
SeWo = input("Введите второе слово: ")
SeWoSet = set(SeWo)
Crosser = set.intersection(FiWoSet, SeWoSet)
Na = len(FiWoSet)
Nb = len(SeWoSet)
Nc = len(Crosser)
T = Nc/(Na+Nb-Nc)
print("Коэффициент сходства слов равен ", T)